set_project("pars")
add_rules("mode.debug", "mode.release", "mode.releasedbg")

-- Third-party baselines are pulled from xmake-repo (not vendored).  cuJSON and
-- simdcsv stay vendored because they are patched for benchmarking (deep source
-- edits), not pristine library usage.
add_requires("simdjson", "toml++", "pugixml", "inih")

target("pars")
    set_kind("headeronly")
    add_headerfiles("include/(pars/**.hpp)")
    add_includedirs("include", {public = true})

target("pars_tests")
    set_kind("binary")
    add_deps("pars")
    add_files("tests/test_model.cpp")
    set_languages("cxxlatest")

-- CPU scan/index throughput vs simdjson (JSON) and simdcsv (CSV).
target("pars_bench")
    set_kind("binary")
    add_deps("pars")
    add_files("bench/bench_scan.cpp")
    set_languages("cxxlatest")
    add_cxxflags("-march=native")

-- Domain SOTA baselines: toml++, pugixml, inih, simdjson (from xmake-repo).
target("pars_bench_baselines")
    set_kind("binary")
    add_deps("pars")
    add_files("bench/bench_baselines.cpp")
    add_packages("simdjson", "toml++", "pugixml", "inih")
    set_languages("cxxlatest")
    add_cxxflags("-march=native")

-- Complete-parser workload on the user-defined hook (GPU stage-1 + user DOM).
target("pars_bench_parse")
    set_kind("binary")
    add_deps("pars")
    add_cugencodes("native")
    add_files("bench/bench_parse.cu")
    add_packages("simdjson")
    add_includedirs("bench")
    set_languages("cxxlatest")

-- pars-side full parse for TOML/XML/INI (GPU R1-R6 + host post-R6 M+D).
target("pars_bench_parse_host")
    set_kind("binary")
    add_deps("pars")
    add_cugencodes("native")
    add_files("bench/bench_parse_host.cu")
    add_includedirs("bench")
    set_languages("cxxlatest")

-- Single-point query latency: pars (index navigation) vs SOTA (DOM lookup).
target("pars_bench_pointquery")
    set_kind("binary")
    add_deps("pars")
    add_cugencodes("native")
    add_files("bench/bench_pointquery.cu")
    add_files("bench/host_pointquery.cpp")
    add_packages("simdjson", "toml++", "pugixml", "inih")
    add_includedirs("bench")
    set_languages("cxxlatest")

-- cuJSON (GPU JSON) reference baseline, reproduced and patched for CUDA 13/CCCL.
target("cujson_baseline")
    set_kind("binary")
    add_cugencodes("native")
    add_files("third_party/cujson/reproduced/cuJSON-standardjson-total-parsing.cu")
    set_languages("cxxlatest")
    add_cuflags("-w", {force = true})

-- Host query tier (GPU stage-1 + lazy user iterator): Parsing / Query / Total.
target("pars_bench_query")
    set_kind("binary")
    add_deps("pars")
    add_cugencodes("native")
    add_files("bench/bench_query.cu")
    add_includedirs("bench")
    set_languages("cxxlatest")

-- Model-M CUDA backend: three-tier boundary benchmark.
target("pars_bench_gpu")
    set_kind("binary")
    add_deps("pars")
    add_cugencodes("native")
    add_files("bench/bench_boundary.cu")
    add_includedirs("bench")
    set_languages("cxxlatest")

-- CSV SOTA baseline (simdcsv) as a standalone binary.
target("simdcsv_baseline")
    set_kind("binary")
    add_files("third_party/simdcsv/main.cpp")
    add_files("third_party/simdcsv/io_util.cpp")
    add_includedirs("third_party/simdcsv")
    add_cxxflags("-march=native", "-include cstdint", {force = true})
    set_languages("cxxlatest")

-- Benchmark configuration for paper_data (xmake f --scales=... --iters=...).
option("scales")
    set_default("8,16,32,64,128,256,512")
    set_description("Benchmark input scales in MB (comma separated)")
option("iters")
    set_default(3)
    set_description("Repetitions per measurement (for mean/p50/p95 distributions)")
option("dataset")
    set_default("")
    set_description("Optional real Standard JSON file (top-level array) used for the cuJSON/simdjson comparison")

-- C-like lexer baseline generated by flex (standard DFA lexer generator).
target("clike_flex_baseline")
    set_kind("binary")
    add_deps("pars")
    add_files("bench/bench_flex_clike.cpp")
    add_files("bench/clike_lex.yy.cpp")
    set_languages("cxxlatest")

-- Deterministic paper-data generation: builds and runs the benchmarks over a
-- fixed set of scales/iterations and writes tidy CSVs for the figures.
-- Run with:  xmake build paper_data
target("paper_data")
    set_kind("phony")
    set_default(false)
    add_deps("pars_bench_gpu", "pars_bench_baselines", "simdcsv_baseline", "clike_flex_baseline",
             "pars_bench_parse", "pars_bench_query", "pars_bench_parse_host",
             "pars_bench_pointquery", "cujson_baseline")
    on_build(function (target)
        -- scales/iters come from xmake options (configure with
        --   xmake f --scales=16,64,256 --iters=10
        -- and rebuild).  Defaults are small so this target never hangs.
        local scales = {}
        for s in tostring(get_config("scales") or "16,64"):gmatch("[^,]+") do
            scales[#scales + 1] = tonumber(s)
        end
        local iters = tonumber(get_config("iters") or 3)
        local dataset = get_config("dataset") or ""
        -- If a real dataset is given, benchmark exactly that file (all formats
        -- and both GPU baselines see the same bytes).
        if dataset ~= "" then
            scales = {math.max(1, math.ceil(os.filesize(dataset) / (1024 * 1024)))}
        end
        local root = os.projectdir()
        local bind = path.join(root, "build", "linux", "x86_64", "release")
        local outdir = path.join(root, "paper", "plots", "data")
        os.mkdir(outdir)

        local pG = path.join(bind, "pars_bench_gpu")
        local bG = path.join(bind, "pars_bench_baselines")
        local pP = path.join(bind, "pars_bench_parse")
        local pQ = path.join(bind, "pars_bench_query")
        local pPQ = path.join(bind, "pars_bench_pointquery")
        local pH = path.join(bind, "pars_bench_parse_host")
        local sd = path.join(bind, "simdcsv_baseline")
        local header = "# format,impl,variant,scale_mb,GBps_mean,GBps_p50,GBps_p95,GBps_min,GBps_max,tokens,bytes_moved"

        local function rows_of(out)
            local t = {}
            for line in out:gmatch("[^\n]+") do
                if line:sub(1, 1) ~= "#" and #line > 0 then t[#t + 1] = line end
            end
            return t
        end

        local pr, br, sr, par, qr = {}, {}, {}, {}, {}
        for _, mb in ipairs(scales) do
            local po = os.iorunv(pG, {tostring(mb), tostring(iters)})
            for line in po:gmatch("[^\n]+") do
                if line:sub(1, 7) == "#stage," then
                    local f = line:match("^#stage,([^,]+),")
                    local rest = line:match("^#stage,[^,]+,(.*)$")
                    if f and rest then sr[#sr + 1] = f .. "," .. tostring(mb) .. "," .. rest end
                elseif line:sub(1, 1) ~= "#" and #line > 0 then
                    pr[#pr + 1] = line
                end
            end
            local bargs = {tostring(mb), tostring(iters)}
            if dataset ~= "" then
                table.insert(bargs, dataset)
            end
            for _, l in ipairs(rows_of(os.iorunv(bG, bargs))) do
                br[#br + 1] = l
            end
            -- complete-parser workload (GPU stage-1 + user hook): JSON
            for _, l in ipairs(rows_of(os.iorunv(pP, {tostring(mb), tostring(iters)}))) do
                par[#par + 1] = l
            end
            -- full parse for TOML/XML/INI (GPU R1-R6 + host post-R6 M+D)
            for _, l in ipairs(rows_of(os.iorunv(pH, {tostring(mb), tostring(iters)}))) do
                par[#par + 1] = l
            end
        end

        -- simdcsv on generated files (distribution over `iters` runs)
        local tmpdir = path.join(root, "build", "paper_csv")
        os.mkdir(tmpdir)
        local rec = 'alpha,beta,"quoted, field","has ""q""",42,true\n'
        for _, mb in ipairs(scales) do
            local csvfile = path.join(tmpdir, "csv_" .. mb .. ".csv")
            local py = string.format(
                "rec=%q\n" .. "t=%d*1024*1024\n" ..
                "f=open(%q,'w')\n" ..
                "while f.tell()<t: f.write(rec.replace('\\\\n','\\n'))\n" ..
                "f.close()\n", rec, mb, csvfile)
            os.execv("python3", {"-c", py})
            local vals = {}
            for _ = 1, iters do
                local out = os.iorunv(sd, {"-i", "3", csvfile})
                local v = out:match("GB/s:%s*([%d%.]+)")
                if v then vals[#vals + 1] = tonumber(v) end
            end
            if #vals > 0 then
                table.sort(vals)
                local q = function(p) return vals[math.max(1, math.min(#vals, math.floor(p * (#vals - 1)) + 1))] end
                br[#br + 1] = string.format("csv,simdcsv,native-ram,%d,%.3f,%.3f,%.3f,%.3f,0,0",
                    mb, q(0.50), q(0.95), vals[1], vals[#vals])
            end
        end

        -- C-like SOTA: flex-generated lexer, over the scales
        local cf = path.join(bind, "clike_flex_baseline")
        for _, mb in ipairs(scales) do
            for _, l in ipairs(rows_of(os.iorunv(cf, {tostring(mb), tostring(iters)}))) do
                br[#br + 1] = l
            end
        end

        -- cuJSON (GPU JSON) reference: H2D + validation + Tokenize + Parser
        -- (their published TOTAL excludes D2H).  Variant encodes the interval.
        local cj = path.join(bind, "cujson_baseline")
        local jdir = path.join(root, "build", "paper_json")
        os.mkdir(jdir)
        -- cuJSON Figure 9 (Standard JSON): match scripts/run_cujson_fig9.sh —
        -- 10 fresh runs, average, parse the last number.  The same source file
        -- (src/reproduced/cuJSON-standardjson-total-parsing.cu) is used.
        local cujson_reps = 10
        for _, mb in ipairs(scales) do
            local jf
            if dataset ~= "" then
                jf = dataset
            else
                jf = path.join(jdir, "json_" .. mb .. ".json")
                os.execv(
                    "python3", {path.join(root, "bench", "gen_json.py"), tostring(mb), jf}
                )
            end
            local vals = {}
            for _ = 1, cujson_reps do
                local out = os.iorunv(cj, {"-b", jf})
                local v = nil
                for n in out:gmatch("([%d%.]+)") do v = n end
                if v then
                    local ms = tonumber(v)
                    if ms and ms > 0 then
                        vals[#vals + 1] = (mb * 1024.0 * 1024.0) / (ms / 1e3) / 1e9
                    end
                end
            end
            if #vals > 0 then
                table.sort(vals)
                local sum = 0
                for _, x in ipairs(vals) do sum = sum + x end
                local q = function(p) return vals[math.max(1, math.min(#vals, math.floor(p * (#vals - 1)) + 1))] end
                br[#br + 1] = string.format("json,cujson,R1-R6+T_in,%d,%.3f,%.3f,%.3f,%.3f,%.3f,0,0",
                    mb, sum / #vals, q(0.50), q(0.95), vals[1], vals[#vals])
            end
        end

        io.writefile(path.join(outdir, "pars.csv"), header .. "\n" .. table.concat(pr, "\n") .. "\n")
        io.writefile(path.join(outdir, "baselines.csv"), header .. "\n" .. table.concat(br, "\n") .. "\n")
        io.writefile(path.join(outdir, "stages.csv"),
            "# format,scale_mb,r1_ms,r2r4_ms,r3r5_ms,r6_ms\n" .. table.concat(sr, "\n") .. "\n")
        io.writefile(path.join(outdir, "parse.csv"), header .. "\n" .. table.concat(par, "\n") .. "\n")
        print("wrote paper/plots/data/{pars,baselines,stages,parse}.csv")
    end)
